<?php $urlSkin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>
<?php //$currency_name = Mage::app()->getLocale()->currency( $currency_code )->getName(); 
$currency_symbol = Mage::app()->getLocale()->currency()->getSymbol(); ?>
<?php if($_GET['success']):
	$generatedCoupon = $_GET['success']; ?>
<?php endif; ?>
<div class="page-title">
    <h1><?php echo $this->__('Fidelity Program'); ?></h1>
</div>
<?php if($this->couponSystemEnabledField()): ?>
	<?php if($generatedCoupon): ?>
		<div class="codebaby-row codebaby-success-msg-row">
			<span class="codebaby-success-txt"><?php echo $this->__('Seu cupom foi gerado com sucesso!') ?></span>
		</div>
	<?php endif; ?>
	<div class="codebaby-row">
		<div class="codebaby-col2">
			<div class="codebaby-featured-box">
				<div class="codebaby-f-left">
					<div class="codebaby-bg-icon" >
						<img src="<?php echo $urlSkin.'frontend/base/default/images/codebaby_fidelityprogram/codebaby-wallet-icon.png'; ?>" alt="">
					</div>
				</div>
				<div class="codebaby-f-left codebaby-padding-zero">
					<p><?php echo $this->__('Você possui:'); ?></p>
					<?php /* ?>
					<p class="codebaby-feat-points"><?php echo $this->getCustomer()->getCustomer_fidelity_points()."<span>".$this->__(' pontos.')."</span>"; ?></p><?php */ ?>
					<?php $customerData = $this->getCustomerCouponInfo($this->getCustomer()); ?>
					<p class="codebaby-feat-points"><?php echo $customerData['customer_fidelity_points']."<span>".$this->__(' pontos.')."</span>"; ?></p>
					<p class="codebaby-feat-points-to-be-confirmed"><?php echo $this->__('And '); ?><span><?php echo $customerData['customer_fidelity_points_to_be_confirmed']; ?></span><?php echo $this->__(' points to be confirmed'); ?></p>
					<?php if($customerData['customer_points_to_sum_next'] != 0): ?>
					<p class="codebaby-feat-points-to-be-confirmed"><?php echo $this->__('+ '); ?><span><?php echo $currency_symbol.$customerData['customer_points_to_sum_next']; ?></span><?php echo $this->__(' to be summed on the next purchase.'); ?></p>
					<?php endif; ?>
				</div>
			</div>
			<div class="codebaby-simple-box">
				<?php if($this->generateCouponButton()): ?>
					<?php $discount = $this->generateCouponButton() ?>
					<?php $url = Mage::getBaseUrl()."coupongenerator/generate?discount=".$discount; ?>
					<form action="<?php echo $url ?>" method="post">
						<button class="button codebaby-generate-bt" type="submit">Generate Coupon</button>
					</form>
				<?php else: ?>
					<p><?php echo $this->__('O botão para gerar seu cupom aparecerá aqui quando você alcançar os pontos necessários.') ?></p>
				<?php endif; ?>
			</div>
			<?php if($this->getCurrentCoupon()): ?>
				<div class="codebaby-simple-box">
					<h5 class="codebaby-row"><?php echo $this->__('Current coupons:') ?></h5>
					<?php foreach ($this->getCurrentCoupon() as $cupom) { ?>
						<?php $codCupom = $cupom['codigo_coupon']; ?>
						<?php if($cupom['is_cupom_used'] == 0): ?>
							<div class="codebaby-cupon-message">
								<p><?php echo $this->__('Use this coupon to get a discount on any product of the store:'); ?></p>
								<p class="codebaby-cod-coupon js-copytextarea">
									<span class="codebaby-js-copytextarea"><?php echo $codCupom; ?></span>
									<!-- <button class="codebaby-js-textareacopybtn"><img src="<?php //echo $urlSkin.'frontend/base/default/images/codebaby_fidelityprogram/codebaby-copy-icon.png'; ?>" alt=""></button> -->
								</p>
							</div>
							<p class="codebaby-cupon-message-addendum"><?php echo $this->__('This coupon is worth: ').$this->getCurrentCouponAmount($codCupom); ?></p>
							<hr class="codebaby-simple-hr" />
						<?php endif; ?>
					<?php } ?>
				</div>
				<script type="text/javascript">
				/* <![CDATA[ *//*
				var copyTextareaBtn = document.querySelector('.codebaby-js-textareacopybtn');
				copyTextareaBtn.addEventListener('click', function(event) {
				  var copyTextarea = document.querySelector('.codebaby-js-copytextarea');
				  // console.log(copyTextarea.innerText); 
				  copyTextarea.innerText.focus();
				  copyTextarea.innerText.select();

				  try {
				    var successful = document.execCommand('copy');
				    var msg = successful ? 'successful' : 'unsuccessful';
				    console.log('Copying text command was ' + msg);
				  } catch (err) {
				    console.log('Oops, unable to copy');
				  }
				});*/
				/* ]]> */
				</script>
					
			<?php endif; ?>
		</div>
		<div class="codebaby-col2">
			<div class="codebaby-box codebaby-bg-box">
				<h3><?php echo $this->__('Regras de Uso:'); ?></h3>
				<p class="codebaby-paragrafo-padrao"><?php echo $this->__('A cada ')."<span class='codebaby-feat-text'>".$currency_symbol.$this->couponSystemMoneyAmount()."</span>".$this->__(' em compras, você acumula ')."<span class='codebaby-feat-text'>".$this->couponSystemPointsPerMoney().$this->__(' pontos.')."</span>"; ?></p>
				<div class="codebaby-box-mini">
					<div class="codebaby-f-left">
						<img src="<?php echo $urlSkin.'frontend/base/default/images/codebaby_fidelityprogram/codebaby-voucher-icon.png'; ?>" alt="">
					</div>
					<div class="codebaby-f-left codebaby-padding-zero">
						<h4><?php echo $this->__('Com ').$this->couponSystemFirstLevelPointsToGet().$this->__('pontos:') ?></h4>
						<p><?php echo $this->__('Você ganha um cupom de desconto de ')."<span>".$currency_symbol.$this->couponSystemFirstLevelCouponDiscount()."</span>"; ?></p>
					</div>
				</div>
				<?php if($this->couponSystemEnableSecondLevel()): ?>
					<div class="codebaby-box-mini">
						<div class="codebaby-f-left">
							<img src="<?php echo $urlSkin.'frontend/base/default/images/codebaby_fidelityprogram/codebaby-voucher-icon.png'; ?>" alt="">
						</div>
						<div class="codebaby-f-left codebaby-padding-zero">
							<h4><?php echo $this->__('Com ').$this->couponSystemSecondLevelPointsToGet().$this->__('pontos:') ?></h4>
							<p><?php echo $this->__('Você ganha um cupom de desconto de ')."<span>".$currency_symbol.$this->couponSystemSecondLevelCouponDiscount()."</span>"; ?></p>
						</div>
					</div>
				<?php endif; ?>
				<?php if($this->couponSystemEnableThirdLevel()): ?>
					<div class="codebaby-box-mini">
						<div class="codebaby-f-left">
							<img src="<?php echo $urlSkin.'frontend/base/default/images/codebaby_fidelityprogram/codebaby-voucher-icon.png'; ?>" alt="">
						</div>
						<div class="codebaby-f-left codebaby-padding-zero">
							<h4><?php echo $this->__('Com ').$this->couponSystemThirdLevelPointsToGet().$this->__('pontos:') ?></h4>
							<p><?php echo $this->__('Você ganha um cupom de desconto de ')."<span>".$currency_symbol.$this->couponSystemThirdLevelCouponDiscount()."</span>"; ?></p>
						</div>
					</div>
				<?php endif; ?>
			</div>
		</div>
	</div>
	<div class="codebaby-simple-box codebaby-conditions-box">
		<div class="codebaby-simple-box">
			<p><?php echo $this->getPromoConditions(); ?></p>
		</div>
	</div>
<?php else: ?>
	<?php echo "not ok"; ?>
<?php endif; ?>
<?php //$this->getCurrentCouponAmount(); ?>
<?php if($this->hasCouponUsed()): ?>
	<?php $customerCouponCollection = $this->hasCouponUsed(); ?>
	<div class="codebaby-row">
		<div class="codebaby-simple-box">
				<h4><?php echo $this->__('Cupom Usage History'); ?></h4>
				<?php foreach ($customerCouponCollection as $usedCoupon) { ?>
					<div class="codebaby-history-box">
						<?php $cuponHistory = $usedCoupon->getData(); ?>
						<p><?php echo $this->__('Cupom Used: '); ?><?php echo $cuponHistory['codigo_coupon']; ?></p>
						<p>|</p>
						<p><?php echo $this->__('Cupom Used on: '); ?><?php echo $cuponHistory['date_used_cupom']; ?></p>
						<p>|</p>
						<p><?php echo $this->__('On Order: '); ?><?php echo "#".$cuponHistory['order_used_cupom']; ?></p>
					</div>
					<hr class="codebaby-simple-hr" />
				<?php } ?>
			</div>
		</div>
<?php endif; ?>